# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rn_j2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rn_j2

  

  target 'rn_j2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  end

  target 'rn_j2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

